config/routes.rb
    resources :domain_blocks, only: [:new, :create, :show, :destroy]
    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]
    resource :settings, only: [:edit, :update]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ }

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show] do
      member do
        post :subscribe
        post :unsubscribe
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
        post :verify
        post :unverify
        post :add_donor_badge
        post :remove_donor_badge
        post :add_investor_badge
        post :remove_investor_badge
        get :edit_pro
        put :save_pro
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :followers, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy] do
      member do
        post :copy
        post :enable
        post :disable
      end
    end

    resources :groups, only: [:index, :destroy] do
      member do
        post :enable_featured
        post :disable_featured
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index] do
      member do
        post :hide
        post :unhide
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
          get :card
        end
      end

      namespace :timelines do
        resource :direct, only: :show, controller: :direct
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
        # resources :group, only: :show
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences, only: [:index]
      resources :trends, only: [:index]

      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      get '/search', to: 'search#index', as: :search

      get '/account_by_username/:username', to: 'account_by_username#show', username: username_regex

      resources :follows,      only: [:create]
      resources :media,        only: [:create, :update]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index]
      resources :favourites,   only: [:index]
      resources :reports,      only: [:create]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
          post :dismiss # Deprecated
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:create, :show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'
        resources :identity_proofs, only: :index, controller: 'accounts/identity_proofs'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      # resources :groups, only: [:index, :create, :show, :update, :destroy] do
      #   member do
      #     delete '/statuses/:status_id', to: 'groups#destroy_status'
      #     post '/statuses/:status_id/approve', to: 'groups#approve_status'
      #   end
      #
      #   resources :relationships, only: :index, controller: 'groups/relationships'
      #   resource :accounts, only: [:show, :create, :update, :destroy], controller: 'groups/accounts'
      #   resource :removed_accounts, only: [:show, :create, :destroy], controller: 'groups/removed_accounts'
      # end

      resources :polls, only: [:create, :show] do
        resources :votes, only: :create, controller: 'polls/votes'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end
    end

    namespace :v2 do
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/',           to: 'about#show', as: :homepage
  get '/about',      to: 'about#more'
  get '/about/tos',  to: 'about#terms'
  get '/about/privacy',      to: 'about#privacy'
  get '/about/investors',    to: 'about#investors'
  get '/about/dmca',         to: 'about#dmca'
  get '/about/sales',        to: 'about#sales'

  get '/tags/:tag', to: 'home#index'
  get '/@:username', to: 'home#index', username: username_regex, as: :short_account
  get '/@:username/with_replies', to: 'home#index', username: username_regex, as: :short_account_with_replies
  get '/@:username/media', to: 'home#index', username: username_regex, as: :short_account_media
  get '/@:username/tagged/:tag', to: 'home#index', username: username_regex, as: :short_account_tag
  get '/@:username/posts/:statusId/reblogs', username: username_regex, to: 'home#index'
  get '/@:account_username/posts/:id', account_username: username_regex, to: 'home#index', as: :short_account_status
  get '/@:account_username/posts/:id/embed', account_username: username_regex, to: 'statuses#embed', as: :embed_short_account_status

  get '/(*any)', to: 'home#index', as: :web
  root 'home#index'

  # Routes that are now to be used within webapp, but still referenced within application
  # TODO : Consolidate
  get '/explore', to: 'directories#index', as: :explore
  get '/explore/:id', to: 'directories#show', as: :explore_hashtag

  resources :tags, only: [:show]

  match '*unmatched_route',
        via: :all,

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  layout 'public'

  before_action :set_instance_presenter, only: [:show, :more, :terms, :privacy, :investors, :dmca, :sales]

  def show
    if user_signed_in?
      redirect_to "/home"
    else
      @hide_navbar = false
    end
  end

  def more; end
  def terms; end
  def privacy; end
  def investors; end
  def dmca; end
  def sales; end

  private

  def new_user
    User.new.tap do |user|
      user.build_account
      user.build_invite_request
    end
  end

  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end
end

app/views/about/_login.html.haml
= simple_form_for(new_user, url: user_session_path) do |f|
  .fields-group
    - if use_seamless_external_login?
      = f.input :email, placeholder: t('simple_form.labels.defaults.username_or_email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.username_or_email') }, hint: false
    - else
      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }, hint: false

    = f.input :password, placeholder: t('simple_form.labels.defaults.password'), input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }, hint: false

    %p.hint.subtle-hint= link_to t('auth.trouble_logging_in'), new_user_password_path
    
  .actions
    = f.button :button, t('auth.login'), type: :submit, class: 'button button-primary'

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  .simple_form__overlay-area
    %p.lead= t('about.federation_hint_html', instance: content_tag(:strong, site_hostname))

    .fields-group
      = f.simple_fields_for :account do |account_fields|
        = account_fields.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username') }, hint: false, disabled: closed_registrations?

      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

    - if approved_registrations?
      .fields-group
        = f.simple_fields_for :invite_request do |invite_request_fields|
          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false

    .fields-group
      = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', about_tos_path: about_tos_path), disabled: closed_registrations?

    .actions
      = f.button :button, sign_up_message, type: :submit, class: 'button button-primary', disabled: closed_registrations?

    - if closed_registrations? && @instance_presenter.closed_registrations_message.present?
      .simple_form__overlay-area__overlay
        .simple_form__overlay-area__overlay__content.rich-formatting
          .block-icon= fa_icon 'warning'
          = @instance_presenter.closed_registrations_message.html_safe

app/views/about/dmca.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h1 SPINSTER LLC
      %h2 COPYRIGHT POLICY

      %h3 Reporting Claims of Copyright Infringement

      %p We take claims of copyright infringement seriously. We will respond to notices of alleged copyright infringement that comply with applicable law. If you believe any materials accessible on or from this site (the “Website”) infringe your copyright, you may request removal of those materials (or access to them) from the Website by submitting written notification to our copyright agent designated below. In accordance with the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (17 U.S.C. § 512) (”DMCA”), the written notice (the “DMCA Notice”) must include substantially the following:

      %ul
        %li Your physical or electronic signature.
        %li Identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works on the Website, a representative list of such works.
        %li Identification of the material you believe to be infringing in a sufficiently precise manner to allow us to locate that material.
        %li Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).
        %li A statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, its agent, or the law.
        %li A statement that the information in the written notice is accurate.
        %li A statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.

      %p Please send copyright notices to support@spinster.xyz

      %p Or via any contact form at the bottom of this page.

      %p If you fail to comply with all of the requirements of Section 512(c)(3) of the DMCA, your DMCA Notice may not be effective.
      %p Please be aware that if you knowingly materially misrepresent that material or activity on the Website is infringing your copyright, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.

      %h3 Counter Notification Procedures
      %p If you believe that material you posted on the Website was removed or access to it was disabled by mistake or misidentification, you may file a counter notification with us (a “Counter Notice”) by submitting written notification to our DMCA address (above) Pursuant to the DMCA, the Counter Notice must include substantially the following:

      %ul
        %li Your physical or electronic signature.
        %li An identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access disabled.
        %li Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).
        %li A statement under penalty of perjury by you that you have a good faith belief that the material identified above was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled.
        %li A statement that you will consent to the jurisdiction of the Federal District Court for the judicial district in which your address is located (or if you reside outside the United States for any judicial district in which the Website may be found) and that you will accept service from the person (or an agent of that person) who provided the Website with the complaint at issue.

      %p The DMCA allows us to restore the removed content if the party filing the original DMCA Notice does not file a court action against you within ten business days of receiving the copy of your Counter Notice.
      %p Please be aware that if you knowingly materially misrepresent that material or activity on the Website was removed or disabled by mistake or misidentification, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.

      %h3 Repeat Infringers

      %p It is our policy in appropriate circumstances to disable and/or terminate the accounts of users who are repeat infringers.

      %hr

      = mail_to 'support@spinster.xyz'

app/views/about/investors.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h2 Investors
      %p
        = link_to 'Invest in Gab', 'https://invest.gab.com'
      %p
        = link_to '2018 Annual Report', 'https://www.sec.gov/Archives/edgar/data/1709244/000114420419021378/tv519744_annualreport.pdf'
      %p
        = link_to '2017 Annual Report', 'https://www.sec.gov/Archives/edgar/data/1709244/000170924418000001/GAB_-_Annual_Report_-_2018.pdf'

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  = javascript_pack_tag 'public', integrity: true, crossorigin: 'anonymous'
  = render partial: 'shared/og'

.content
  .box-widget
    .rich-formatting= @instance_presenter.site_extended_description.html_safe.presence || t('about.extended_description_html')

  %br

  .box-widget
    .rich-formatting
      %h3 Open Source
      %p
        Spinster is free and open source (FOSS) software licensed under the GNU Affero General Public License version 3 (AGPL3).
        It's based on #{link_to 'Gab Social', 'https://code.gab.com/gab/social/gab-social', target: "_blank"}, which is in turn forked from #{link_to 'Mastodon', 'https://github.com/tootsuite/mastodon/', target: "_blank"}.
      %p Source code: #{link_to "https://gitlab.com/spinster-xyz/spinster", "https://gitlab.com/spinster-xyz/spinster", target: "_blank"}

app/views/about/sales.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.content
  .box-widget
    .rich-formatting
      %h2 Terms of Sale
      %p Spinster LLC (“We” or “Spinster”) hereby allow you to access certain premium features or content in exchange for a one-time or recurring fee, as applicable to the relevant features or content, such as our “SpinsterPro” enhanced social media offering (collectively, each a “Paid Service” and collectively the "Paid Services"). Your transactions and any other use of the Paid Services are subject to these Spinster Paid Service Terms of Service ("Terms”).

      %h3 1. Your Acceptance
      %p
        By using a Paid Service, you signify your agreement to (1) these Terms of Sale; and (2) Spinster LLC’s
        = link_to 'Terms of Service', about_tos_path
        ,
        = link_to 'Privacy Notice', about_privacy_path
        , and
        = link_to 'Copyright Notice', about_dmca_path
        , and all other terms and conditions that generally apply to the Website (as such term is defined in the Terms of Service).  Please read the Terms carefully. If you do not understand the Terms, or do not accept any part of them, then you may not use the Paid Services.
      %p Each time you place an order for a Paid Service (including when you order individual subscriptions or items of content), you enter into a separate contract for services on these Terms. When you complete a purchase, you signify that you wish to enter into a binding contract for the provision of the applicable Paid Services.

      %h3 2. Payment, Refund and Cancellation Policy
      %p Spinster accepts payment via the current payment method indicated prior to purchase, which may include Bitcoin and/or any other form of payment that we make available to you from time to time. You must tender valid payment or have a valid accepted form of payment on file in order to purchase Paid Services or participate in free trial offers or other free offers related to the Paid Services. You agree to abide by any relevant Terms of Service or other legal agreement, whether with Spinster or a third party, that governs your use of a given payment processing method. Prices for any Paid Service may change at any time, and Spinster does not provide price protection or refunds in the event of a price reduction or promotional offering. You agree to pay for any Paid Service that you order. Spinster will charge your credit card or other form of payment for the price listed on the relevant Paid Service offer, along with any additional amounts relating to applicable taxes, bank fees and currency fluctuations. If you purchase any automatically renewing subscriptions, you agree that Spinster will charge the payment method on file on the first day of each billing period for the relevant subscription, and if the payment method on file becomes invalid due to an expired credit card or other similar reason and we are unable to charge you on the next billing period, Spinster reserves the right to immediately revoke your access to any Paid Service you have ordered until you update your payment method. If you fail to update your payment method within a reasonable amount of time, Spinster may cancel your subscription.
      %p If Spinster is required to collect or pay any taxes in connection with your purchase of a Paid Service, such taxes will be charged to you at the time of each purchase transaction. Additionally, if required by law, you are responsible for reporting and paying certain taxes in connection with your purchase and use of a Paid Service. Such taxes may include duties, customs fees, or other taxes (other than income tax), along with any related penalties or interest, as applicable to your purchase or country of purchase.

      %p
        %b REFUNDS:
        all purchases are final.

      %p
        %b SUBSCRIPTION CANCELLATIONS:
        you purchase a subscription to a Paid Service that automatically renews, you may cancel the subscription any time before the end of the current billing period and the cancellation will take effect on the next billing period. You will retain access to the Paid Service from the time you cancel until the start of the next billing period, and will not receive a refund or credit for any remaining days in your current billing period.

      %p
        %b FREE TRIALS:
        Spinster may offer free trials to new Paid Service subscribers. If you purchase a subscription to a Paid Service that includes a free trial, you will receive free access to such Paid Service for the duration of the free trial period. At the end of the applicable free trial period, you will be charged the price of the subscription and will continue to be charged until you cancel your subscription. To avoid any charges, you must cancel before the end of the free trial period.

      %h3 3. Accessing Paid Services.
      %p Certain types of Paid Services may require you to use a device that meets the system and compatibility requirements for such Paid Service, which may change from time to time. You shall have sole responsibility for obtaining a device which satisfies those requirements.

      %h3 4. License
      %p Your use of the Paid Services must be only for personal, non-commercial use. You agree not to use any Paid Service, in whole or in part in connection with any public presentation even if no fee is charged (except where such use would not constitute a copyright infringement). You are receiving a non-exclusive license to access the Paid Service and all rights, title and interest in the Paid Services (including any content offered through the Paid Services) not expressly granted to you in these Terms are reserved by Spinster and its licensors. If Spinster reasonably determines that you violated any of the terms and conditions of the Paid Service Terms, your rights under this Section 4 will immediately terminate and Spinster may terminate your access to the Paid Service and/or your Spinster account without notice and without refund to you.

      %h3 5. Restrictions
      %p When you use the Paid Service, you may not (or attempt to):

      %ul
        %li violate the Terms of Service;
        %li use the Paid Service in an illegal manner or for an illegal purpose;
        %li share your account password with someone else to allow them to access any Paid Service that such person did not order;
        %li copy, sell, rent, or sublicense the Paid Services to any third party;
        %li circumvent, reverse-engineer, modify, disable, or otherwise tamper with any security technology that Spinster uses to protect the Paid Service or encourage or help anyone else to do so;
        %li access the Paid Service other than by means authorized by Spinster; or
        %li remove any proprietary notices or labels on Paid Services.

      %h3 6. Changes
      %p Spinster reserves the right to change the availability and content of the Paid Services at any time with or without notice to you. In addition, we reserve the right to modify, suspend, or discontinue any Paid Service with or without notice to you and we will not be liable to you or any third party for any such modifications, suspension, or termination. However, this will not affect your ability to request a refund as described above.
      %p
        In certain cases, content available within a Paid Service may become unavailable. Spinster will have no liability to you for any such unavailability. We may also change these Paid Service Terms from time to time so we encourage you to periodically review the most up-to-date version at
        = link_to 'https://spinster.xyz/about/sales'
      %p If the Paid Service Terms change, you will have the opportunity to review the new terms when you next purchase any Paid Service. By completing the purchase, you signify your agreement to the new Paid Service Terms, and further, that they will apply to your use of the Service as a whole (including any Paid Service you have purchased in the past) and all subsequent purchases (until the Paid Service Terms change again). If you refuse to accept the updated Paid Service Terms then you may not buy any additional Paid Services and the latest version of the Paid Service Terms that you accepted will continue to apply to your use of previously purchased Paid Services.

      %h3 7. Communications
      %p By using the Paid Services, you consent to receiving communications from us including marketing communications such as newsletters about Spinster features and content, special offers, promotional announcements, and customer surveys, to your registered email address or via other methods.

      %h3 9. Other Terms
      %p You acknowledge and agree that certain content available in the Paid Services may be considered offensive to some people and that such content may not be labeled as such. Additionally, certain descriptions of Paid Services or content available in the Paid Services are not guaranteed to be accurate. You agree to use the Paid Services at your own risk and, subject to applicable laws, Spinster will have no liability to you for any content that you find offensive .

      %p The Paid Services are being provided by Spinster LLC.

app/views/about/show.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %link{ rel: 'canonical', href: about_url }/
  = render partial: 'shared/og'

.landing
  .landing-columns
    .landing-columns--left
      .landing__brand
        = link_to root_url, class: 'brand' do
          = image_pack_tag 'gab_logo.svg', alt: 'Gab Social'
        %span.brand__tagline=t 'about.tagline'

    .landing-columns--right
      .box-widget
        = render 'registration'